version: 2

updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 0 # disables version update PRs
    groups:
      security-updates:
        applies-to: security-updates
        patterns:
          - "*"
