version: 2

updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
    # Disable all updates except security updates
    open-pull-requests-limit: 0  # Prevents version update PRs