version: 2

updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 2 # disables version update PRs
    groups:
      security-updates:
        applies-to: security-updates
        patterns:
          - "*"
      nice-to-have:
        patterns:
          - "@ngrx/*"
        applies-to: version-updates
