name: Prevent old branches in pull requests
run-name: Verifying that branch age is not older than max allowed days
decription: Reinforcement of the short-lived branch strategy, hindering the merge if more than a certain maximum number of days have passed.

env:
    max-days: 3 # define the maximum allowed branch age in days

runs:
  using: 'composite'

  steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        fetch-depth: 0  # Needed to access full git history and remote branches

    - name: Set up Git
      shell: bash
      run: |
        git fetch origin main 

    - name: Check branch age
      id: branch-creation-date
      shell: bash
      run: |
        BRANCH_NAME="${{ github.head_ref }}"
        echo "Checking branch age for: $BRANCH_NAME"

        branch_creation_date=$(git log --reverse --format=%aI $(git merge-base origin/main origin/$BRANCH_NAME)..origin/$BRANCH_NAME | head -n 1)
        current_date=$(date -u +"%Y-%m-%dT%H:%M:%SZ")
        branch_age=$(( ($(date -u -d $current_date +%s) - $(date -d $branch_creation_date +%s)) / 86400 ))

        echo "Branch creation date: $branch_creation_date"
        echo "Current date: $current_date"
        echo "Branch age (in days): $branch_age"
        echo "env.max-days (in days): ${{ env.max-days }}"

        if [ "$branch_age" -gt "${{ env.max-days }}" ]; then
          echo "❌ Branch is too old: $branch_age days (maximum allowed is ${{ env.max-days }} days)"
          exit 1
        fi

        echo "✅ Branch age is acceptable: $branch_age days"
