name: Check Branch Age

on:
  #push:
  #  branches:
  #    - '**'  # Triggers on push to any branch
  pull_request:
    branches:
      - main  # or your default branch

jobs:
  check-branch-age:
    runs-on: ubuntu-latest
    env:
      max-days: 14  # Set your max branch age in days here

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Needed to access full git history and remote branches

      - name: Set up Git
        run: |
          git fetch origin main

      - name: Check branch age
        run: |
          branch_creation_date=$(git log --reverse --format=%aI $(git merge-base HEAD origin/main)..HEAD | head -n 1)
          current_date=$(date -u +"%Y-%m-%dT%H:%M:%SZ")
          branch_age=$(( ($(date -u -d $current_date +%s) - $(date -d $branch_creation_date +%s)) / 86400 ))
          
          echo "Branch creation date: $branch_creation_date"
          echo "Current date: $current_date"
          echo "Branch age (in days): $branch_age"
          
          if [ "$branch_age" -gt "${{ env.max-days }}" ]; then
            echo "Branch is too old: $branch_age days (maximum allowed is ${{ env.max-days }} days)"
            exit 1
          fi
          echo "Branch age is acceptable: $branch_age days"
