name: Check Branch Age on PR

on:
  pull_request:
    branches:
      - main  # or your default branch

jobs:
  call-branch-age-check:
    uses: uaman89/.github/.github/workflows/check-branch-age.yml@main